name: assignment661
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+4 # Use the latest compatible version
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Updated for compatibility with Flutter 3

flutter:
  uses-material-design: true
  assets:
    - assets/a.jpeg
    - assets/b.png
    - assets/c.png
