name: assignment661
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+4
  speech_to_text: ^7.0.0
  intl: ^0.18.0
  google_maps_flutter: ^2.2.0  # Keep only one instance of this dependency
  firebase_storage: ^12.3.7
  geolocator: ^10.0.1
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Ensure the assets directory is properly included
  assets:
    - assets/d.jpg
    - assets/e.jpg
    - assets/a.png
    - assets/b.png
    - assets/c.png
    - assets/f.jpg
    - assets/g.jpg
    - assets/h.jpg
    - assets/i.jpg
    - assets/j.jpg
    - assets/k.jpg
    - assets/l.jpg
    - assets/m.jpg
    - assets/n.jpg
    - assets/p.png
    - assets/q.jpg
    - assets/room.jpg
    - assets/profile.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
 
